USE DanfossDrives;

INSERT INTO Products (ProductName, MinVoltage, MaxVoltage, MinPower, MaxPower, ProductDetails, ProductFeatures)
VALUES
('VLT Compact Starter MCD 200', 200, 480, 7.5, 110, 'Two series of soft starters that provide a total motor starting solution for motors up to 110 kW. The MCD 201 compact starter offers efficient motor-starting features, while the extended MCD 202 version of the compact starter provides enhanced soft-start functionality and additional motor-protection features. The series of soft starters offer easy DIN rail mounting for sizes up to 30 kW, 2-wire or 3-wire start/stop control and excellent starting duty (4 x le for 6 seconds; heavy starting ratings at 4 x le for 20 seconds). They are compatible with grounded delta power systems.', 'Easy connectivity for the soft starter to Ethernet/IP-based networks, such as Rockwell PLC systems Panel space can be saved due to the compact size Installation costs are minimized and power loss eliminated thanks to the built-in bypass More starts per hour and a higher load is possible as a result of advanced SCR Control Algorithms that balance output waveform Overall project investment is reduced due to essential motor protections No external cooling or oversizing is necessary thanks to the maximum ambient temperature of 50-C without derating'),
('VLT Soft Starter MCD 600', 200, 690, 20, 1250, 'Superior soft start performance for fixed-speed applications The VLT- Soft Starter MCD 600 combines the latest in advanced controls and protections with an increased level of intelligence for superior performance in fixed-speed applications. The MCD 600 is more flexible than ever to install, thanks to a wide variety of Ethernet and serial-based communication option cards, application-dedicated smart cards and support for eight languages. An integrated bypass ensures both extremely high efficiency and harmonic-free operation at full speed, reducing energy consumed and required cooling capacity. Ease of use is in focus with features such as the pump-clean function, PowerThrough operation, and calendar or run time-based scheduling. More extensive motor and starter protections ensure more uptime.', 'Inbuilt impeller cleaning assistance with Pump clean functionality Easy application analysis with up to 348 events logged, as well as QR code scan for serial number and event data Easy data access and reduced startup and upgrade time thanks to integrated USB port More reliability, more uptime with expanded motor and controller protections Flexibility for low speed applications, with Jog function Improved uptime with PowerThrough function which uses 2-phase control if one phase is damaged by shorted SCR Easy connectivity for the soft starter to Ethernet-based networks, such as PROFINET and EtherNet/IP Programming is quick and easy thanks to three menu systems (Quick Menu, Application Setup and Main Menu), a four-line graphical display and a logic keypad The best starting and stopping profile for the application is chosen using Adaptive Acceleration Control (AAC) Installation costs are lower and there is less stress on the motor thanks to DC injection braking distributed evenly over three phases Save space and reduce installation costs, thanks to the internal bypass contactors Good asset protection thanks to Emergency mode, which keeps the fan or pump running for as long as possible in an emergency'),
('VLT AQUA DRIVE FC 202', 200, 690, 0.25, 1400, 'Maximum energy efficiency for water and wastewater applications The VLT- AQUA Drive is designed to provide the highest level of performance of AC-motor-driven water and wastewater applications. Featuring a wide range of powerful standard features, which can be expanded with performance-improving options, the drive is equally suited to both new and retrofit projects. The considerable daily load variation in water or wastewater treatment plants makes it economically feasible to introduce motor control on rotating equipment such as pumps and blowers. VLT AQUA Drive can offer first-year cost savings of between 10-30% compared to traditional variable speed drive solutions. Its high lifetime availability and low energy consumption and maintenance costs provide you with the lowest cost of ownership. The quick and user-friendly setup of water and pump settings reduces installation time ensuring a fast route to maximum energy efficiency and motor control. By collecting the most important parameters in one place, the risk of incorrect configuration is reduced significantly.', 'Protect your assets well with specially designed software which prevents damage by water hammering and more Maximize energy efficiency thanks to control algorithms and design which focus on reducing heat loss Save energy on air conditioning with the unique back-channel-cooling concept that transfers 90% of heat away from the room Reduce electromagnetic interference and harmonic distortion thanks to the built-in, scalable RFI filter and integrated DC link chokes Integrate perfectly into your system and adapt precisely to the application using freely programmable warnings and alerts Win 3-8% more energy savings as a result of Automatic Energy Optimization Use condition-based monitoring to optimize uptime in your pumping applications'),
('VACON 100 FLOW', 208, 690, 0.55, 800, 'Dedicated functionality for pumps, fans and compressors VACON- 100 FLOW is an AC drive that is dedicated to improving flow control and saving energy in industrial pump and fan applications. Specifically designed features include Multipump solutions and application selection menus. They enhance pump performance and protect pipes and equipment to ensure reliable operation. Standard PID control uses a sensor to control pump speed instead of an external controller. This helps the drive to quickly react to fluctuations in demand for accurate process control and optimized energy savings.', 'Features and benefits Fast and efficient system integration thanks to dedicated functionality for pump, fan and compressor applications Extended drive lifetime and minimized lifecycle costs due to electrolytic-free DC link capacitors Easy commissioning and start-up as a result of graphical keypad and wizard guides Efficient integration into automation systems thanks to built-in Ethernet and RS485 communication'),
('VLT Midi Drive FC 280', 200, 480, 0.37, 22, 'Flexible, communicative and easy to use. Fits your application Reach new levels of performance with the VLT- Midi Drive FC 280, the evolution of the popular VLT- 2800 drive. Profit from new savings with a wide range of features designed to make installing, using and maintaining the AC drive as simple and as easy as possible. For precise and efficient motor control for machine builders in the food and beverage, material handling and processing industries, the VLT- Midi Drive is ideal. It is strong on control performance, functional safety and flexible fieldbus communication. VLT- Midi Drive is designed for compatibility with the VLT- 2800. Its exterior dimensions, connectors, cable lengths and set-up software tools allow you to easily retrofit an established drive panel.', 'Compact design saves panel space Easy and fast installation set-up due to flexible user interfaces No need to install extra cooling equipment or oversize the drive as it is designed to operate at 45-C at full load and up to 55-C with derating No need to install extra components thanks to integrated harmonic mitigation, RFI filters, brake choppers and functional safety (STO) Integrated active Power Factor Correction (PFC) significantly reduces harmonic distortion and improves power supply quality'),
('VLT Micro Drive FC 51', 200, 480, 0.18, 22, 'Maximum strength with reduced installation costs The VLT- Micro Drive FC 51 is small and yet powerful and built to last. Panel space can be saved and installation costs reduced thanks to its compact size and minimal commissioning requirements. Despite its compact size and easy commissioning, the VLT- Micro Drive can be set up to perform perfectly even in complex applications. It is supported by guided programming of specific functions and the use of a PC software tool for parameterizing. And, thanks to its coated PCBs, the drive ensures reliable and cost-effective operation also in demanding environments.', 'Side-by-side mounting without derating is possible thanks to the compact, book-style design Penetration of dust is minimized thanks to coated PCBs Radio disturbance from motor cables is limited due to built-in RFI filters Lifetime of the drive is extended and reliability improved as a result of the effective heat sink that removes heat from the electronics Energy consumption can be reduced as kinetic energy in the application can be transformed into braking power to slow down the motor'),
('VLT Micro Drive FC 21', 200, 480, 0.18, 15, 'Stable and reliable, the perfect combination of stability and performance VLT - Micro Drive FC 21 is compact, easy to use, stable and reliable. Small size saves cabinet space. Lean operation and longer service life. VLT - Micro Drive FC 21 is not only compact and easy to commission, but also uses high-quality electronic components to achieve true reliability and maximum operating time. It comes standard with a pluggable control panel and supports PC software tool MCT10. The printed circuit board (PCB) with reinforced coating ensures that the drive can operate reliably and cost-effectively even in harsh environments.', 'Book-type design, can be placed side by side without reducing the rated value, saving installation space Independent air duct to prevent dust intrusion Standard coated circuit boards ensure longer service life and reliability Highly efficient heat sink dissipates heat away from electronic components, extending drive life and improving reliability Efficient cooling function allows the inverter to operate at an ambient temperature of 50-C without derating'),
('iC2-Micro', 200, 480, 0.37, 22, 'Performance that pays off This quality general purpose drive is a perfect match for a wide range of applications. iC2-Micro performs with unsurpassed reliability even in complex applications. It gives you user-friendliness, condensed functionality, and easy commissioning, all in a powerful compact package. More compact, intelligent, and powerful than its predecessor, the iC2-Micro is designed as an easy replacement for VLT- Micro Drive FC 51. This reliable and durable drive is even easier to use and install. You can reduce system complexity and cost whilst maintaining full performance. This drive gives you excellent motor control and mechanical brake performance. New features include torque open loop control, locked motor detection, permanent magnet motor control, built-in control panel', 'Scan QR code to get product information fast Fast and accurate installation with spring type I/O terminals for minimal external wiring Fast commissioning thanks to application wizards and online/offline PC configuration tool High reliability Cost-effective and space-efficient investment with less wiring, side-by-side mounting and compact footprint Compatible with all typical motor technologies and supported by the powerful MyDrive- Suite digital tools Optional external control panel provides extra features to ease commissioning, such as parameter copy and download'),
('VLT HVAC Drive FC 102', 200, 690, 1.1, 1400, 'Get more out of your HVAC drive - low life cycle costs in all climates Even better reliability and lower total costs for heating, ventilation and air conditioning (HVAC) installations with a unique VSD design optimized for building management systems. Due to extreme climates, difficult-to-access machine rooms and isolated stations, HVAC installations require the best process control solutions on the planet. They are also needed to control day-to-day critical operations and expensive systems, because competition and efficiency requirements are constantly getting tougher. The improved VLT- HVAC Drive provides room to operate. It defeats the problems and offers strong reliability, with favorable life cycle costs.', 'Lighten your overall costs . The constant demand for lower total costs is a challenge that the VLT- HVAC Drive can help meet. It can be installed outdoors even in extreme climates . You can use this frequency converter completely reliably outdoors at extreme temperatures of +50 ... -25 -C. Saves time. You can configure the drive parameters and perform troubleshooting from outside the air handling unit (AHU) using the wireless LCP . The freedom to choose the engine you want . Compatibility with all typical motor technologies means you can choose the motor of your choice, whether for supply security or performance optimization. Take advantage of the freedom of data transmission . Compatibility with all typical motor technologies means you can choose the motor of your choice, whether for supply security or performance optimization. Maximize uptime: Integrated health monitoring uses sensors, including the VLT- PTU 025 pressure transmitter , to detect system changes at an early stage Improve the energy efficiency of the system with the EC+ concept'),
('VLT Automation Drive FC 301', 200, 690, 0.25, 1400, 'Powerful, reliable and gorgeous This durable frequency converter works efficiently and reliably even in the most demanding applications and in the most challenging environments. VLT- AutomationDrive takes full advantage of the new possibilities of the digital age, meets the requirements of your application and optimizes your process throughout its entire life cycle. State-of-the-art thermal design and unique rear channel cooling make the VLT- AutomationDrive one of the most compact and cost-effective devices on the market. Intelligent maintenance and monitoring functions improve the productivity, performance and usability of the systems in the long term.', 'Suitable for all motor technologies and fieldbus protocols: widely compatible Plug and play technology makes commissioning and upgrades easy The rear channel cooling solution reduces energy costs and the size of the cooling system and extends the life cycle of the frequency converter Automatic Motor Adaptation (AMA) for fast starting Automatic energy optimization (AEO) improves system efficiency Safe stop and Safe Torque Off ensure safe operation of the frequency converter The integrated motion controller (IMC) makes automation easy Condition monitoring (CBM) is integrated to achieve the best possible utilization rate in your operations Custom commissioning with VLT - Motion Control Tool MCT 10 Check out the free software tools and downloads for MyDrive- Suite The reinforced structure reduces possible negative effects caused by vibration DrivePro- Life Cycle services proactively improve the utilization rate of your facility VLT- FlexConcept improves efficiency and simplifies the system'),
('VLT Automation Drive FC 302', 200, 690, 0.25, 1400, 'Powerful, reliable and gorgeous This durable frequency converter works efficiently and reliably even in the most demanding applications and in the most challenging environments. VLT- AutomationDrive takes full advantage of the new possibilities of the digital age, meets the requirements of your application and optimizes your process throughout its entire life cycle. State-of-the-art thermal design and unique rear channel cooling make the VLT- AutomationDrive one of the most compact and cost-effective devices on the market. Intelligent maintenance and monitoring functions improve the productivity, performance and usability of the systems in the long term.', 'Suitable for all motor technologies and fieldbus protocols: widely compatible Plug and play technology makes commissioning and upgrades easy The rear channel cooling solution reduces energy costs and the size of the cooling system and extends the life cycle of the frequency converter Automatic Motor Adaptation (AMA) for fast starting Automatic energy optimization (AEO) improves system efficiency Safe stop and Safe Torque Off ensure safe operation of the frequency converter The integrated motion controller (IMC) makes automation easy Condition monitoring (CBM) is integrated to achieve the best possible utilization rate in your operations Custom commissioning with VLT - Motion Control Tool MCT 10 Check out the free software tools and downloads for MyDrive- Suite The reinforced structure reduces possible negative effects caused by vibration DrivePro- Life Cycle services proactively improve the utilization rate of your facility VLT- FlexConcept improves efficiency and simplifies the system'),
('VLT Automation Drive EZ FC 321', 200, 690, 0.25, 149.2, 'For basic drive applications you don not want to sift through a laundry list of features to customize your drive and wait for delivery; you want an AC Drive with a low number of variants that easy to stock, ships quick when needed, and is simple to startup with plug and play convenience. We heard you and thats why we are proud to introduce the VLT- AutomationDrive EZ FC 321. For variable speed control of all asynchronous and permanent magnet motors, on any industrial machine or production line, this VFD is packed with standard features right off the shelf with no special configuration or customization required. Save energy, improve flexibility, and optimize processes with this intelligent yet simple variable frequency drive designed for easy stocking and fast turnaround - Because every motor deserves the best AC Drive', 'Flexible and expandable: With a flexible modular design, the AutomationDrive EZ FC 321 is packed with standard features which can be expanded with plug-and-play options with additional features and fieldbuses. Safe Torque-Off is a standard safety feature that can be applied through hardwired safety. Printed circuit board protection: Drives up to 100 HP conforms to class 3C2 (IEC 60721-3-3) as standard. Drives above 100 HP come standard with 3C3. Robust and reliable: VLT- AutomationDrive EZ FC 321 is a proven performer in all industrial environments and grid voltages, including 690V. Enclosures are available up to NEMA 4X (depending on model), and integrated DC chokes and RFI filters in all models protect installations by minimizing harmonic distortion and electromagnetic interferences. All drives are tested at full-load before leaving the factory. Easy set up and commissioning: The VLT- AutomationDrive EZ FC 321 is easy to set up and operate via the user-friendly graphical control panel, requires minimal maintenance, and delivers a market leading control solution which provides a fast return on investment with a highly competitive cost of ownership. Smart Start wizard: Includes groups for several of the most common applications, including conveyors, pumps and fans, and setup with mechanical brake. With the settings to run applications already in place, you can get your machine up and running faster, increasing your productivity.'),
('VACON NXP Air Cooled', 208, 690, 0.55, 4500, 'VACON- NXP Air Cooled drives offer precision and power to applications that require a robust and dynamic performance. Available in a complete power range up to 2 MW, they are provided as wall-mounted, standalone enclosed and IP00 modules. The drives provide optimized motor control for both induction and permanent magnet motors, and gearless drive applications and paralleling solutions for high-power motors. Fast fieldbus options and exceptional programming flexibility ensure the drives are easily integrated into any plant-s automation system. Engineering time and costs can be saved due to the high number of standardized options and reduced system complexity.', 'Easy integration into any plant-s automation system thanks to fast fieldbus options and exceptional programming flexibility Investment costs are minimized as no additional external modules are needed and the drives are supplied with five built-in expansion slots for additional I/O, fieldbus and functional safety boards Fast response to changes due to dynamic open- and closed-loop vector control The drive-s DC fans fulfill the ERP2015 directive on decreasing fan losses and significantly increase the reliability and lifetime of the fan The lifetime of the drive and critical components are extended as a result of coated printed circuit boards that offer reliable protection against dust and moisture'),
('VACON 100 INDUSTRIAL', 208, 690, 0.55, 800, 'VACON- 100 INDUSTRIAL is full of features and dedicated for a wide range of constant power/torque applications. The easy-to-use and robust motor controls improve the reliability and efficiency of all AC motor types, including induction and permanent magnet and synchronous reluctance motors. Integrated RS485 and Ethernet interfaces support all major industrial protocols making VACON 100 INDUSTRIAL easy to incorporate into all major control systems. The built-in PLC functionality enables integration of new functionality into the drive. Functional safety is improved with Safe Torque Off, which prevents the motor from generating torque on the motor shaft, Safe Stop 1 and ATEX-certified motor over-temperature protection. The wall-mountable drive modules are easy to install and operate, and the enclosed drives are provided with a wide range of integrated options.', 'Easy integration with plant automation due to extensive range of fieldbus options High reliability in challenging environments as a result of conformal coating Extended drive lifetime thanks to film capacitors No additional accessories are required due to integrated RFI filters and DC choke'),
('VLT AQUA Drive FC 202 ED', 200, 690, 0.25, 1400,'VLT- AQUA Drive is designed to guarantee the best possible performance in electric motor driven water and wastewater applications. With a wide range of powerful standard functions that can be expanded with performance-enhancing accessories, it is suitable for both new projects and retrofits. The load of water and wastewater treatment plants varies considerably from day to day, which is why it is economically viable to add motor control to rotating equipment such as pumps and fans. VLT AQUA Drive can bring cost savings of 10-30% in the first year compared to traditional variable speed drive solutions. Its long service life, low energy consumption and low maintenance costs guarantee low life cycle costs. Water and pump settings can be set quickly and easily, which reduces installation time and quickly ensures the best possible energy efficiency and motor control. When the most important parameters are gathered in the same place, the risk of incorrect settings is greatly reduced.' ,'Protect your device with specially designed software that prevents damage caused by, for example, pressure shocks Control algorithms and a new structure that reduces heat losses maximize energy efficiency Save energy spent on air conditioning with a unique rear channel cooling concept that transfers 90% of the heat out of the room Built-in RFI filter and integrated intermediate circuit chokes reduce electromagnetic interference and harmonic distortion Perfectly integrate into your system and precisely adapt to your application with freely programmable warnings and alarms Automatic energy optimization increases energy savings by 3-8% Optimize the availability of pump applications with condition monitoring'),
('VLT Decentral Drive FCD 302', 380, 480, 0.37, 3,'Designed for simplicity and robustness, the VLT- Decentral Drive FCD 302 is a user-friendly product with high performance and a strong protection degree. A decentral-drive solution eliminates the need for space-consuming control cabinets. And, with the drives placed near the motor, there is no need for long-screened motor cables. With the VLT Decentral Drive FCD 302, all the options are built into the unit reducing the number of boxes to be mounted, and the connections and terminations in the installation. As a result, labor costs and the risks of failure are dramatically reduced.' ,'Installation is flexible as the drive adapts to any brand of motor Servicing is fast and easy due to the pluggable twin-part design Cleaning is easy thanks to the drive-s smooth surface Cable savings are possible as a result of the integrated power and fieldbus looping terminals Direct connection to a PC is possible thanks to the integrated USB port The need for PLC capacity is reduced due to the built-in smart logic controller'),
('VACON 100X', 208, 240, 1.1, 15,'The VACON- 100 X frequency converter features advanced control capabilities for almost any type of application where a distributed and sustainable solution is the best option. All power parts, including harmonic current filtering chokes, are assembled in one compact and sturdy unit. The individual junction box contains the control unit and all frequency converter connections, freeing up space elsewhere.         Thanks to IP66/type 4X Outdoor housing, the frequency converter is suitable for harsh environments. It can be placed either on top of the engine or as close as possible to the engine equipment. This makes it very suitable for retrofitting, roof applications and machinery that is regularly washed. Cabinets, shielded cabling and electrical rooms are not needed. The large cooling fins on the front of the frequency converter housing cool without collecting dust. They enable efficient use of the cooling element and can be cleaned with pressurized water, which makes maintenance easy and operation reliable.' ,'Withstands harsh conditions such as heat, dirt and vibration Easy to keep clean The installation is flexible and suitable for public networks thanks to the built-in filter chokes for harmonic currents Integrated Ethernet communication and safe torque off (STO) Can be installed in any position and is suitable for all spaces'),
('VLT HVAC Drive FC 102 ED', 200, 690, 1.1, 1400,'Even better reliability and lower total costs for heating, ventilation and air conditioning (HVAC) installations with a unique VSD design optimized for building management systems. Due to extreme climates, difficult-to-access machine rooms and isolated stations, HVAC installations require the best process control solutions on the planet. They are also needed to control day-to-day critical operations and expensive systems, because competition and efficiency requirements are constantly getting tougher. The improved VLT- HVAC Drive provides room to operate. It defeats the problems and offers strong reliability, with favorable life cycle costs.' ,'Lighten your overall costs . The constant demand for lower total costs is a challenge that the VLT- HVAC Drive can help meet. It can be installed outdoors even in extreme climates . You can use this frequency converter completely reliably outdoors at extreme temperatures of +50 ... -25 -C. Saves time. You can configure the drive parameters and perform troubleshooting from outside the air handling unit (AHU) using the wireless LCP . The freedom to choose the engine you want . Compatibility with all typical motor technologies means you can choose the motor of your choice, whether for supply security or performance optimization. Take advantage of the freedom of data transmission . Compatibility with all typical motor technologies means you can choose the motor of your choice, whether for supply security or performance optimization. Maximize uptime: Integrated condition monitoring uses sensors, including the VLT- PTU 025 pressure transmitter , to detect system changes at an early stage Improve the energy efficiency of the system with the EC+ concept'),
('VLT Decentral Servo Drive DSD 520', 565, 680, 3, 3,'The VLT- Decentral Servo Drive DSD 520 extends the VLT- FlexMotion- decentral servo drive concept. Supporting a wide range of feedback encoders and sensorless control, its architecture is completely open and allows you to choose your preferred PM or ACM motor. Use the Integrated Motion Controller (IMC) to run the motion sequence independently and free up capacity in the central PLC.' ,'The extensive VLT- FlexMotion portfolio with a mix of central and decentral components fits perfectly into modular machine concepts Supports various encoder feedback systems and expands the freedom of of PM servo and ACM motor selection Fast and fail-safe wiring concept helps to save installation time and component costs Open connectivity to common real time Ethernet protocols allows flexibility, fast process communication and easy system integration VLT- FlexSafety- support of advanced functional safety: PROFIsafe and FSoE (Safety over EtherCAT) PLCopen certified Motion libraries and IEC 61131-3 programming provide a standardized and easy system approach across controller platforms Comprehensive real-time system data from each component strongly supports predictive and preventive machine maintenance Vibration resistance according to 3M7 and IP67 protection ratings ensures reliable operation in demanding environments Servo drive mounted directly on or nearby the motor reduces cabinet space requirement and costs for cooling equipment'),
('VLT OneGearDrive OGD', 380, 480, 0.75, 2.2,'The VLT- OneGearDrive- is a highly efficient, permanent magnet, three-phase synchronous motor coupled with an optimized bevel gear box and IE5 ultra premium efficiency which helps to optimize plant productivity and reduce energy costs. With only one motor type and three available gear ratios, the motor concept covers all typical versions of conveyor drives commonly used in the food and beverage industry. The reduced range of physical configurations reduces costs and simplifies spare-part storage. Uniform mechanical dimensions reduce engineering and installation time and costs. The drive comes in two versions: Standard for use in dry and wet production areas and Hygienic for use in wet areas and environments with high cleaning intensity including aseptic and cleanroom production areas.' ,'Up to 40% energy savings compared to conventional systems thanks to high system efficiency with an IE5 motor Less noise and no airborne germs and dirt particles drawn into motor and expelled back into the surrounding air due to fan-free operation Unrestricted use and high protection in wash-down areas thanks to high degrees of protection Easy to clean due to smooth enclosure design Fast, reliable connection and lower installation costs as a result of motor and brake connections via terminal box with CageClamp- technology Resistance to detergents and disinfectants thanks to aseptic coating'),
('VACON NXP System modules ari cooled', 208, 690, 0.55, 4500,'VACON- NXP Air Cooled drives offer precision and power to applications that require a robust and dynamic performance. Available in a complete power range up to 2 MW, they are provided as wall-mounted, standalone enclosed and IP00 modules. The drives provide optimized motor control for both induction and permanent magnet motors, and gearless drive applications and paralleling solutions for high-power motors. Fast fieldbus options and exceptional programming flexibility ensure the drives are easily integrated into any plant-s automation system. Engineering time and costs can be saved due to the high number of standardized options and reduced system complexity.' ,'Easy integration into any plant-s automation system thanks to fast fieldbus options and exceptional programming flexibility Investment costs are minimized as no additional external modules are needed and the drives are supplied with five built-in expansion slots for additional I/O, fieldbus and functional safety boards Fast response to changes due to dynamic open- and closed-loop vector control The drive-s DC fans fulfill the ERP2015 directive on decreasing fan losses and significantly increase the reliability and lifetime of the fan The lifetime of the drive and critical components are extended as a result of coated printed circuit boards that offer reliable protection against dust and moisture'),
('VACON NXC', 380, 690, 110, 2000,'The enclosed VACON- NXC is the compact drive that performs reliably in harsh operating conditions in, for example, the mining, oil and gas or water and wastewater industries. The thermally managed enclosure extends drive lifetime and ensures trouble-free operation. The enclosures, which feature lifting lugs for easy handling, can be either wall-mounted or free-standing. The easily accessible control compartment for relays, auxiliary terminals and other equipment, and ample space around the power terminals ensure straightforward installation and connection of power cables. And the mounting rails and pull-out jig enable fast and efficient servicing of the power unit.' ,'Lower investment cost as no extra design, engineering or additional cooling fans are needed Reduced commissioning and servicing time due to easily accessible control compartment and removable keypad Improved serviceability thanks to mounting rails and service concept with pull-out jig Lower maintenance costs due to robust, type-tested design'),
('VACON NXP System Drive (SM)', 380, 690, 415, 5976,'"VACON- NXP System Drive is a comprehensive Common DC Bus product for heavy industry use, where round-the-clock operation is required and little time is left for maintenance.' ,'Savings in maintenance costs and optimized cash flow, because the modules can be delivered closer to the start of use due to quick installation Cost savings brought by a standardized solution Quick setup and maintenance thanks to modular design and pull-out mechanism Minimized downtime, because spare parts are always conveniently available in stock'),
('VACON NXC Low Harmonics', 380, 690, 110, 2000,'The enclosed VACON- NXC is the compact drive that performs reliably in harsh operating conditions in, for example, the mining, oil and gas or water and wastewater industries. The thermally managed enclosure extends drive lifetime and ensures trouble-free operation. The enclosures, which feature lifting lugs for easy handling, can be either wall-mounted or free-standing. The easily accessible control compartment for relays, auxiliary terminals and other equipment, and ample space around the power terminals ensure straightforward installation and connection of power cables. And the mounting rails and pull-out jig enable fast and efficient servicing of the power unit.' ,'Lower investment cost as no extra design, engineering or additional cooling fans are needed Reduced commissioning and servicing time due to easily accessible control compartment and removable keypad Improved serviceability thanks to mounting rails and service concept with pull-out jig Lower maintenance costs due to robust, type-tested design'),
('VACON 100 FLOW ED', 208, 690, .55, 800,'VACON- 100 FLOW is a frequency converter specially designed to improve flow control and save energy in industrial pump and fan applications. Application-specific features include Multipump solutions and application selection menus. They improve pump performance and protect pipes and equipment, guaranteeing reliable operation. A standard PID controller uses a sensor instead of an external controller to control the speed of the pump. It helps the frequency converter to react quickly to fluctuations in the need for precise process control and optimized energy saving.' ,'System integration is fast and efficient thanks to functions designed especially for pump, fan and compressor applications Longer drive life cycle and minimal life cycle costs thanks to electrolyte-free DC link capacitors Easy commissioning and start-up with graphical control panel and guided functions Efficient integration into automation systems thanks to built-in Ethernet and RS485 communication'),
('VACON 100 Industrial SM', 208, 690, .55, 800,'VACON- 100 INDUSTRIAL is full of various features and specially designed for numerous different continuous power/torque applications. Easy-to-use and rugged motor controllers improve the reliability and efficiency of all types of AC motors, including induction motors, permanent magnet and synchronous reluctance motors. One frequency converter for many different applications VACON- 100 INDUSTRIAL is full of various features and specially designed for numerous different continuous power/torque applications. Easy-to-use and rugged motor controllers improve the reliability and efficiency of all types of AC motors, including induction motors, permanent magnet and synchronous reluctance motors. The integrated RS485 and Ethernet interfaces support all major industrial protocols, which makes VACON 100 INDUSTRIAL easy to connect to all major control systems. The built-in PLC function enables the integration of new functions into the frequency converter. The safety of the operation is improved by the accidental start prevention (Safe Torque Off, STO), which prevents the motor from producing torque on the motor shaft, the Safe Stop 1 safety function, and ATEX-certified protection against motor overheating. Wall-mounted frequency converters are easy to install and easy to use, and cabinet-mounted frequency converters contain plenty of integrated accessories.' ,'Easy connection to factory automation thanks to numerous fieldbus options Very reliable in challenging environments thanks to uniform coating The frequency converter has a longer than normal life cycle thanks to the membrane capacitors Thanks to the integrated FRI filters and DC choke, no additional accessories are needed' ),
('VACON 100 Industrial ED', 208, 690, .55, 800,'VACON- 100 INDUSTRIAL is full of various features and specially designed for numerous different continuous power/torque applications. Easy-to-use and rugged motor controllers improve the reliability and efficiency of all types of AC motors, including induction motors, permanent magnet and synchronous reluctance motors. One frequency converter for many different applications VACON- 100 INDUSTRIAL is full of various features and specially designed for numerous different continuous power/torque applications. Easy-to-use and rugged motor controllers improve the reliability and efficiency of all types of AC motors, including induction motors, permanent magnet and synchronous reluctance motors. The integrated RS485 and Ethernet interfaces support all major industrial protocols, which makes VACON 100 INDUSTRIAL easy to connect to all major control systems. The built-in PLC function enables the integration of new functions into the frequency converter. The safety of the operation is improved by the accidental start prevention (Safe Torque Off, STO), which prevents the motor from producing torque on the motor shaft, the Safe Stop 1 safety function, and ATEX-certified protection against motor overheating. Wall-mounted frequency converters are easy to install and easy to use, and cabinet-mounted frequency converters contain plenty of integrated accessories.' ,'Easy connection to factory automation thanks to numerous fieldbus options Very reliable in challenging environments thanks to uniform coating The frequency converter has a longer than normal life cycle thanks to the membrane capacitors Thanks to the integrated FRI filters and DC choke, no additional accessories are needed' ),
('iC7-Automation Enclosed Drives', 380, 500, 200, 900,'Whatever the environment, the iC7-Automation delivers the reliability and performance you need. With connectivity, security and intelligence, this drive lets you take advantage of the latest in Industrial IoT. iC7-Automation gives you a whole new way to optimize your system with selectable communication protocols and Safe Torque Off (STO) SIL3 as standard. The modular control platform allows you to expand functionality to meet your needs.' ,'- Streamlined system integration - Fast and safe service access - 6-pulse, low-harmonic, and regenerative variants - Intelligent heat management - Modular control - Small footprint thanks to cutting-edge heat management - Wide range of cabinet options' ),
('iC7-Automation Air-Cooled SM', 380, 500, 200, 2700,'Whatever the environment, the iC7-Automation delivers the reliability and performance you need. With connectivity, security and intelligence, this drive lets you take advantage of the latest in Industrial IoT. iC7-Automation gives you a whole new way to optimize your system with selectable communication protocols and Safe Torque Off (STO) SIL3 as standard. The modular control platform allows you to expand functionality to meet your needs.' ,'Highly compact design saves space and reduces cooling costs - Integrated dual Ethernet port with multiple fieldbus protocols for flexible operation, free of stock costs and lead time - Safe Torque-Off up to SIL3 / PLe as standard for highest reliability and easier certification - Numerous integrated sensors improve performance and control accuracy - Virtual models to speed up and de-risk development projects - Integration unit with built-in filters reduces integration cost - Increase power by paralleling power units without balancing filters - Fast power unit replacement without removing motor cables - Modular and scalable control concept - Efficient heat management with back-channel cooling.' ),
('VACON 3000 Enclosed Drive', 3300, 4160, 1620, 7060,'When uptime is everything, this drive gives you reliability you can count on in heavy-duty engineering applications. The VACON- 3000 Enclosed Drive is a modular and configurable cabinet-built drive delivering superior performance, complexity reduction and easy maintenance. When robustness, space and weight are crucial to competitiveness this drive has you covered on all counts. For ordinary installation conditions, choose these pre-engineered drives to save time and reduce complexity. You can be sure of robust reliable performance despite high ambient temperatures and tough environments, with IP54/NEMA 3S protection and an innovative integrated cooling system.' ,'Maximize operating uptime with robust design featuring IP54 ingress protection, liquid cooling and full power operation up to 45-C ambient temperature Speed up engineering and installation with straightforward selection of drive and options, proven quality, very small footprint and simple commissioning process Easy serviceability with front access and easy exchange phase module Get equipped for the future with state-of-the-art 3L-NPC topology, AFE (low harmonic) or 12-pulse DFE configuration, modularity based on single-phase modules, Brake Chopper Unit (BCU) option, and other pre-engineered options' ),
('VACON 1000', 2400, 11000, 150, 12960,'Danfoss- unsurpassed experience in advanced AC drive technologies makes the VACON- 1000 air-cooled MV drive the preferred choice for industrial medium-voltage general purpose applications, especially for variable torque loads such as pumps and fans in the low and mid-power range. The standalone version, available at 215 A and below, is one of the most compact and versatile multi-level MV drives in its class.' ,'Reliable High MTBF with up to 200,000 hours of non-stop operation 100% full-load burn-in tested before shipping for fast commissioning and start-up Detailed fault monitoring for reduced downtime Redundant cooling fan enables non-stop operation in case of fan failure Safe and user-friendly Simple, easy selections for a wide variety of flexible configurations Front access only allows for easy installation, service and maintenance Complies with international MV drive safety requirements according to applicable IEC and UL standards Space saving Smallest footprint in the market available at 215 A and below (?6.9 kV) Stand-alone design for fast, simple installation Simple cable installation with top and bottom cabling entry' ),
('VACON NXP Grid Converter', 380, 690, 160, 1800,'The VACON- NXP Grid Converter plays a key role in supporting clean power conversion in distributed networks with or without energy storage. By enabling connection of energy storage to AC grids, supporting hydrogen electrolysis, and facilitating AC grids onboard vessels or island applications in remote areas, it fulfils a unique function. Without the grid converter none of these would be possible.  The grid converter facilitates load sharing and is highly versatile, for easy integration into diverse networks. Its importance cannot be overstated; use of a grid converter is a must in reaching emission targets.' ,'Reduced fuel consumption as electrical power can be sourced from the grid Lower CO2, NOx and SOx emissions as the main engine can be shut down Conforms to ABS and DNV standards Improved energy efficiency as engine speed can be optimized Liquid and air cooled solutions available Facilitates fast system certification for distributed smart grids, thanks to compliance with global grid codes Protects critical industrial processes with Intelligent DC backup Simplified logistics and good protection with containerized solutions Faster, more cost effective engineering thanks to reference designs Facilitates active and reactive load sharing via droop function' ),
('VACON NXP DC Guard', 460, 1100, 0.4, 4140,'VACON- NXP DCGuard- enables fast disconnection and full selectivity be-tween DC grids for all VACON- NXP series drives. Utilizing DC grids rather than AC grids enables power distribution with lower power losses. However, ensuring selectivity and limited short circuit energy requires more sophisticated protection devices. VACON- NXP DCGuard is a semiconduc-tor protection device that maintains the stability of the DC grid by detecting and cutting off any faulty DC currents, fast. It isolates the faulty part of the system within 5 microseconds, protecting the surrounding equipment and ensuring uninterrupted operation. It has DNV-GL, ABS, and Lloyds Register type approvals, simplifying system approval for use in marine environments.' ,'Correct system selectivity due to short circuit protection No overvoltage spikes at current cut-off Connect two different DC grids with voltage differences up to full DC voltage, thanks to controlled voltage ramp-up Transmission cable overload protection Reliable, proven technology'),
('VACON NXP DC/DC', 380, 690, 380, 690,'Due to the wide input range of the source voltages, for example battery, the VACON- NXP DC/DC Converter application can be used to match source voltage to a common DC bus system. This method utilizes the stored energy to create the right DC bus voltage required to operate the machinery running on these hybrid systems. VACON- NXP DC/DC Converter is well suited to containerized energy storage solutions. Scalable solutions mean you can easily balance the grid while growing your plant. The VACON- NXP DC/DC Converter application can be installed in both liquid- and air-cooled VACON- NXP drive modules.' ,'Using the same VACON- NXP hardware and control platform, DC/DC converters require very little additional investment for the same amount of system flexibility A modular solution, DC/DC converters are easily added to the DC bus of a system providing almost instant access to additional DC sources and easy expansion Utilizing the same VACON- NXP hardware configurations, service teams require little to no additional training Wide range of current ratings ensures simpler integration of an extensive variety of common battery bank voltages Aging battery stacks are easy to replace to ensure reduced downtime Compatible with a wide variety of DC voltage sources or energy storage mediums' ),
('VLT Automation Drive FC 302', 200, 690, 0.25, 1156,'The VLT- AutomationDrive is designed for variable speed control of all asynchronous motors and permanent magnet motors. It comes in a standard version (FC 301) and an advanced high dynamic version (FC 302) with additional functionalities. It helps save energy, increase flexibility, reduce costs related to spare parts and servicing, and optimize process control on any industrial machine or production line. The VLT AutomationDrive is built on a flexible, modular design concept to provide versatile control. Its robust construction ensures maximum uptime. It comes equipped with a wide range of standard industry features which can be expanded with -plug-and-play- options. The user-friendly graphical control panel ensures the drive is easy to set up and operate saving commissioning and operating costs. Enclosures are available up to Nema 4X (depending on the model). Integrated DC chokes and RFI filters in all models protect installations by minimizing harmonic distortion and electromagnetic interference. The VLT AutomationDrive can also be used with applications that need to perform high-precision positioning and synchronization operations. The Integrated Motion Controller (IMC) functionality is now configurable in the drive-s software. No additional modules or hardware are necessary. All drives are fully tested already at the factory. They require very little maintenance and provide a fast return on investment.' ,'There-s less need for cooling or oversizing as the ambient temperature ranges from -13F to 122F without derating  The need for PLC capacity is reduced thanks to Smart Logic Control  Low lifetime costs are ensured as the drive is highly resistant to wear and tear The lifetime of electronics is prolonged due to back-channel cooling for frames D, E and F  Commissioning and upgrades are easy due to plug-in technology High-precision position and synchronization thanks to availability of Integrated Motion Controller throughout the entire product range Features such as intelligent heat management, Safe stop and Safe Torque Off ensure safe and energy-efficient operation of the drive' ),
('VACON NXP LIquid Cooled ED', 400, 690, 700, 1550,'VACON- NXP Liquid Cooled drives are integrated in a sturdy enclosure making them ideal for a wide range of industries with harsh operating conditions. Liquid-cooled AC drives can be used in many combinations, from a single dedicated frequency converter to large-scale common DC bus systems. Packed with features, these fully standardized enclosed drives maximize the utilization of space while minimizing overall lifecycle costs. Thanks to the high degree of protection (IP54), these drives can be installed almost anywhere in a plant or on a vessel. This eliminates the load on air-conditioning systems in electrical rooms reducing costs and installation time, and makes them ideal for retrofitting. Servicing is fast and easy. Features such as safe torque off (STO) and safe stop 1 (SS1) improve safety, and conformal coated circuit boards enhance reliability.' ,'Drive lifetime and reliability are enhanced due to sturdy cabinet protection Floor space requirements and infrastructure needs are reduced as the compact design needs no air ducts Investment savings as no large air-conditioning systems are needed due to minimal dissipation of heat loss to the air Fulfills all relevant international standards and global requirements including marine, safety, EMC and harmonics approvals Virtually silent operation as no large cooling fans are needed' ),
('VACON NXP LIquid Cooled SM', 400, 690, 110, 5300,'With one of the best power/size ratios, VACON- NXP Liquid Cooled drives are ideal for applications where space is at a premium or air cooling is difficult. Heavy industries with harsh operating conditions, such as in marine, offshore and mining environments benefit from the drive-s compact design and robust reliability.' ,'Floor space requirements and infrastructure needs are reduced as the compact design needs no air ducts Investment savings as no large air-conditioning systems are needed due to minimal dissipation of heat loss to the air Fulfills all relevant international standards and global requirements including marine, safety, EMC and harmonics approvals Virtually silent operation as large cooling fans are not needed' ),
('iC7-Marine CM SM', 380, 690, 170, 6400,'Enter a new dimension of opportunities with this ultra-compact drive. As well as high power density, iC7-Marine gives you a powerful combination of intelligence and shaft performance, ready for the most challenging of applications. iC7-Marine is equipped with a world-class IoT security approach that enables you to future-proof your system for the decades ahead. Enjoy unparalleled performance and ease of system integration: for propulsion, thrusters, winches and more.' ,'Secure-by-design to reduce risk of downtime caused by unauthorized access High power density saves space and reduces cooling costs Native integration of filters below the power units saves space and reduces installation costs Highly accurate motor control saves costs and improves performance Modular control architecture improves performance by adapting to the needs of the application Integrated Ethernet communication interfaces save cost and time in installation Numerous integrated sensors improve performance and control accuracy Expandable, encrypted microSD card-based memory securely records data for offline analysis' ),
('iC7-Marine Liquid-cooled SYstem Modules', 380, 690, 170,6400 ,'Enter a new dimension of opportunities with this ultra-compact drive. As well as high power density, iC7-Marine gives you a powerful combination of intelligence and shaft performance, ready for the most challenging of applications. iC7-Marine is equipped with a world-class IoT security approach that enables you to future-proof your system for the decades ahead. Enjoy unparalleled performance and ease of system integration: for propulsion, thrusters, winches and more.' ,'Secure-by-design to reduce risk of downtime caused by unauthorized access High power density saves space and reduces cooling costs Native integration of filters below the power units saves space and reduces installation costs Highly accurate motor control saves costs and improves performance Modular control architecture improves performance by adapting to the needs of the application Integrated Ethernet communication interfaces save cost and time in installation Numerous integrated sensors improve performance and control accuracy Expandable, encrypted microSD card-based memory securely records data for offline analysis' );



INSERT INTO Industries (IndustryName)
VALUES
('Food, Beverage & Packing'),
('Mining and Cement'),
('Chemical'),
('Cranes & Hoists'),
('Elevators & Escalators');


INSERT INTO Applications (ApplicationName)
VALUES
('Centrifuges & Decanters'),
('Charging'),
('Compressors'),
('Conveyors'),
('Cranes & Hoists'),
('Extruders'),
('Drilling'),
('Elevators'),
('Escalators'),
('Energy Storage'),
('Fans & Dryers'),
('Mills, Drums, Kilns'),
('Power Conversion System PCS'),
('Positioning, Sync'),
('Process & Material Treatment'),
('Pumps'),
('Winches, Tensioners'),
('Grinder & Roller'),
('Mixer'),
('Dosing systems'),
('Kneader'),
('Crusher'),
('Material Handling');


INSERT INTO Product_Industry (ProductID, IndustryID)
VALUES
(1, 2),
(1, 3),
(2, 2),
(2, 3), 
(3, 2),
(4, 2),
(5, 1),
(5, 2),
(5, 3),
(5, 4),
(5, 5),
(6, 2),
(6, 3),
(6, 4),
(7, 3),
(8, 1),
(8, 2),
(8, 3),
(8, 4),
(9, 2),
(10, 5),
(11, 2),
(11, 3),
(11, 4),
(11, 5),
(12, 3),
(13, 2),
(13, 3),
(13, 4),
(13, 5),
(14, 2),
(14, 3),
(15, 2),
(16, 1),
(16, 2),
(16, 3),
(17, 2),
(17, 3),
(18, 2),
(19, 1),
(20, 1),
(21, 2),
(21, 3),
(21, 4),
(22, 2),
(22, 3),
(22, 4),
(23, 2),
(23, 3),
(23, 4),
(24, 2),
(24, 3),
(24, 4),
(25, 2),
(26, 3),
(27, 2),
(27, 3),
(28, 2),
(28, 3),
(28, 4),
(29, 2),
(29, 3),
(29, 4),
(30, 2),
(31, 2),
(31, 3),
(32, 1),
(32, 3),
(32, 4),
(33, 1),
(33, 3),
(34, 1),
(34, 2),
(34, 3),
(34, 4),
(35, 2),
(35, 4),
(36, 2),
(36, 4),
(37, 2),
(37, 4),
(38, 4),
(39, 4);




-- For Food & Beverage, Packing Industry
INSERT INTO Product_Application (ProductID, IndustryID, ApplicationID)
VALUES
(1, 2, 4),
(1, 2, 11),
(1, 2, 16),
(1, 3, 4),
(1, 3, 11),
(1, 3, 16),
(2, 2, 3),
(2, 2, 4),
(2, 2, 11),
(2, 2, 16),
(2, 3, 3),
(2, 3, 4),
(2, 3, 11),
(2, 3, 16),
(2, 3, 19),
(3, 3, 16),
(4, 2, 11),
(4, 2, 16),
(5, 1, 1),
(5, 1, 3),
(5, 1, 4),
(5, 1, 5),
(5, 1, 11),
(5, 1, 16),
(5, 2, 4),
(5, 2, 11),
(5, 2, 16),
(5, 3, 3),
(5, 3, 15),
(5, 3, 4),
(5, 3, 11),
(5, 3, 18),
(5, 3, 19),
(5, 3, 20),
(5, 3, 22),
(5, 3, 23),
(5, 4, 5),
(5, 5, 9),
(6, 2, 4),
(6, 2, 11),
(6, 2, 16),
(6, 3, 4),
(6, 3, 5),
(6, 3, 11),
(6, 3, 15),
(6, 3, 16),
(6, 3, 18),
(6, 3, 19),
(6, 3, 20),
(6, 3, 21),
(6, 3, 22),
(6, 3, 23),
(6, 4, 5),
(7, 3, 4),
(7, 3, 11),
(7, 3, 15),
(7, 3, 16),
(7, 3, 18),
(7, 3, 19),
(7, 3, 20),
(7, 3, 21),
(7, 3, 22),
(7, 3, 23),
(8, 1, 3),
(8, 1, 4),
(8, 1, 5),
(8, 1, 11),
(8, 2, 4),
(8, 2, 11),
(8, 2, 16),
(8, 3, 4),
(8, 3, 11),
(8, 3, 15),
(8, 3, 16),
(8, 3, 18),
(8, 3, 19),
(8, 3, 20),
(8, 3, 21),
(8, 3, 22),
(8, 3, 23),
(8, 4, 5),
(9, 2, 11),
(10, 5, 9),
(11, 2, 1),
(11, 2, 3),
(11, 2, 4),
(11, 2, 7),
(11, 2, 11),
(11, 2, 12),
(11, 2, 15),
(11, 2, 16),
(11, 2, 17),
(11, 3, 1),
(11, 3, 3),
(11, 3, 4),
(11, 3, 11),
(11, 3, 12),
(11, 3, 15),
(11, 3, 16),
(11, 3, 17),
(11, 3, 18),
(11, 3, 19),
(11, 3, 20),
(11, 3, 21),
(11, 3, 22),
(11, 3, 23),
(11, 4, 5),
(11, 5, 8),
(11, 5, 9),
(12, 3, 1),
(12, 3, 3),
(12, 3, 4),
(12, 3, 6),
(12, 3, 11),
(12, 3, 12),
(12, 3, 15),
(12, 3, 16),
(12, 3, 18),
(12, 3, 19),
(12, 3, 20),
(12, 3, 21),
(12, 3, 22),
(12, 3, 23),
(13, 2, 1),
(13, 2, 3),
(13, 2, 4),
(13, 2, 5),
(13, 2, 7),
(13, 2, 11),
(13, 2, 12),
(13, 2, 14),
(13, 2, 15),
(13, 2, 16),
(13, 2, 18),
(13, 2, 19),
(13, 2, 20),
(13, 2, 21),
(13, 2, 22),
(13, 2, 23),
(13, 3, 1),
(13, 3, 3),
(13, 3, 4),
(13, 3, 5),
(13, 3, 11),
(13, 3, 12),
(13, 3, 15),
(13, 3, 16),
(13, 3, 18),
(13, 3, 19),
(13, 3, 20),
(13, 3, 21),
(13, 3, 22),
(13, 3, 23),
(13, 4, 5),
(13, 5, 8),
(13, 5, 9),
(14, 2, 3),
(14, 2, 4),
(14, 2, 11),
(14, 2, 15),
(14, 2, 16),
(14, 3, 1),
(14, 3, 3),
(14, 3, 4),
(14, 3, 11),
(14, 3, 12),
(14, 3, 15),
(14, 3, 16),
(14, 3, 18),
(14, 3, 19),
(14, 3, 20),
(14, 3, 21),
(14, 3, 22),
(14, 3, 23),
(15, 2, 16),
(16, 1, 4),
(16, 2, 3),
(16, 3, 4),
(17, 2, 3),
(17, 3, 1),
(17, 3, 3),
(17, 3, 4),
(17, 3, 11),
(17, 3, 16),
(17, 3, 19),
(17, 3, 20),
(18, 2, 11),
(19, 1, 14),
(20, 1, 4),
(21, 2, 2),
(21, 2, 3),
(21, 2, 4),
(21, 2, 5),
(21, 2, 7),
(21, 2, 11),
(21, 2, 12),
(21, 2, 15),
(21, 2, 16),
(21, 3, 1),
(21, 3, 3),
(21, 3, 6),
(21, 3, 11),
(21, 3, 12),
(21, 3, 16),
(21, 4, 5),
(22, 2, 1),
(22, 2, 3),
(22, 2, 4),
(22, 2, 5),
(22, 2, 7),
(22, 2, 11),
(22, 2, 12),
(22, 2, 15),
(22, 2, 16),
(22, 2, 17),
(22, 3, 1),
(22, 3, 3),
(22, 3, 4),
(22, 3, 11),
(22, 3, 12),
(22, 3, 15),
(22, 3, 16),
(22, 4, 5),
(23, 2, 1),
(23, 2, 3),
(23, 2, 10),
(23, 2, 12),
(23, 2, 17),
(23, 3, 1),
(23, 3, 3),
(23, 3, 11),
(23, 3, 12),
(23, 3, 17),
(23, 4, 5),
(24, 2, 1),
(24, 2, 3),
(24, 2, 4),
(24, 2, 5),
(24, 2, 7),
(24, 2, 11),
(24, 2, 12),
(24, 2, 15),
(24, 2, 16),
(24, 2, 17),
(24, 3, 1),
(24, 3, 3),
(24, 3, 4),
(24, 3, 11),
(24, 3, 12),
(24, 3, 15),
(24, 3, 16),
(24, 4, 5),
(25, 2, 11),
(25, 2, 17),
(26, 3, 1),
(26, 3, 3),
(26, 3, 11),
(26, 3, 12),
(26, 3, 16),
(27, 2, 3),
(27, 2, 4),
(27, 2, 11),
(27, 2, 15),
(27, 2, 16),
(27, 3, 1),
(27, 3, 3),
(27, 3, 4),
(27, 3, 11),
(27, 3, 12),
(27, 3, 15),
(27, 3, 16),
(27, 3, 18),
(27, 3, 19),
(27, 3, 21),
(27, 3, 22),
(27, 3, 23),
(28, 2, 1),
(28, 2, 3),
(28, 2, 4),
(28, 2, 5),
(28, 2, 7),
(28, 2, 11),
(28, 2, 12),
(28, 2, 15),
(28, 2, 16),
(28, 2, 17),
(28, 3, 1),
(28, 3, 3),
(28, 3, 4),
(28, 3, 6),
(28, 3, 11),
(28, 3, 12),
(28, 3, 15),
(28, 3, 16),
(28, 3, 18),
(28, 3, 19),
(28, 3, 22),
(28, 3, 23),
(28, 4, 5),
(29, 2, 1),
(29, 2, 3),
(29, 2, 4),
(29, 2, 5),
(29, 2, 7),
(29, 2, 11),
(29, 2, 12),
(29, 2, 15),
(29, 2, 16),
(29, 2, 17),
(29, 3, 1),
(29, 3, 3),
(29, 3, 4),
(29, 3, 6),
(29, 3, 11),
(29, 3, 12),
(29, 3, 16),
(29, 4, 5),
(30, 2, 11),
(30, 2, 12),
(30, 2, 16),
(30, 2, 17),
(31, 2, 3),
(31, 2, 7),
(31, 2, 11),
(31, 2, 12),
(31, 2, 15),
(31, 2, 16),
(31, 2, 17),
(31, 3, 1),
(31, 3, 3),
(31, 3, 11),
(31, 3, 12),
(31, 3, 16),
(32, 1, 10),
(32, 1, 13),
(32, 3, 10),
(32, 4, 5),
(33, 1, 10),
(33, 1, 13),
(33, 3, 10),
(34, 1, 10),
(34, 1, 13),
(34, 2, 2),
(34, 3, 10),
(34, 4, 5),
(35, 2, 1),
(35, 2, 3),
(35, 2, 4),
(35, 2, 5),
(35, 2, 7),
(35, 2, 11),
(35, 2, 12),
(35, 2, 14),
(35, 2, 15),
(35, 2, 16),
(35, 2, 17),
(35, 4, 5),
(36, 2, 1),
(36, 2, 3),
(36, 2, 4),
(36, 2, 5),
(36, 2, 7),
(36, 2, 11),
(36, 2, 12),
(36, 2, 14),
(36, 2, 15),
(36, 2, 16),
(36, 2, 17),
(36, 4, 5),
(37, 2, 1),
(37, 2, 3),
(37, 2, 4),
(37, 2, 5),
(37, 2, 7),
(37, 2, 11),
(37, 2, 12),
(37, 2, 14),
(37, 2, 15),
(37, 2, 16),
(37, 2, 17),
(37, 4, 5),
(38, 4, 5),
(39, 4, 5);


